package:
  name: nspdk
  version: 9.2

source:
  fn: NSPDK-9.2.tar.gz
  url: https://raw.githubusercontent.com/BackofenLab/GraphClust/master/NSPDK_src/NSPDK-9.2.tar.gz
  sha256: 90955549e7d3e268d194cb89a38018a323f050c1c524d35630733f4cd97664a6

build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]

  run:
    - libgcc    # [not osx]

test:
  commands:
    - NSPDK -h >/dev/null

about:
  home: http://dtai.cs.kuleuven.be/ml/systems/nspdk
  license: 
  license_file: 
  summary: Neighborhood Subgraph Pairwise Distance Kernel (NSPDK).
